export enum AffineErrorCode {
  INVALID_CONFIG = 'INVALID_CONFIG',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED',
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  GRAPHQL_ERROR = 'GRAPHQL_ERROR',
  HTTP_ERROR = 'HTTP_ERROR',
  UNEXPECTED_RESPONSE = 'UNEXPECTED_RESPONSE',
  NOT_SIGNED_IN = 'NOT_SIGNED_IN',
  SYNC_ERROR = 'SYNC_ERROR',
}
